#this option allows items in ANY inventory slot to affect the player, instead of only armour and hands.
#NOTE: This may cause/increase lag on your server.
fullchecking: false

#users without the permission "itemcreatorplus.nosavelimit" will have a max amount of items that can be created
#set this to -1 to have no saved item cap
saveitemlimit: 5

#setting this to false will stop showing the "You have been given" message on /icp give
givemessage: true

#if set to true, player effects will stack. (ex: speed 3 + speed 3 = speed 4)
#if set to false, the max effect will be applied (ex: speed 5 + speed 2 = speed 5)
stackingeffects: true

#if an item has this line of lore on it, it cannot be placed
noplace: '&cCannot be placed'
