name: ItemCreatorPlus
version: 1.10.9
author: Darkolythe
main: me.darkolythe.itemcreatorplus.ItemCreatorPlus
api-version: 1.13
description: This plugin allows easy creation of custom items with potion effects, attributes, and more, all in a simple GUI.

commands:
  itemcreatorplus:
    usage: /<command>
    aliases: [icp]
    description: the itemcreatorplus base command
    permission: itemcreatorplus.command
    permission-message: You do not have permission!

permissions:
  itemcreatorplus.command:
    description: basic command permission
    default: op
  itemcreatorplus.savemenu:
    description: lets the player open up the list of saved items
    default: op
  itemcreatorplus.giveitem:
    description: allows the user to give ICP items to players via the /icp give command (can be used in console), and take saved items from the ICP save menu
    default: op
  itemcreatorplus.enchant:
    description: allows the user to open and use the enchant section of ICP
    default: op
  itemcreatorplus.status:
    description: allows the user to open and use the status effects section of ICP
    default: op
  itemcreatorplus.saveitem:
    description: allows the user to save custom items
    default: op
  itemcreatorplus.lore:
    description: allows the user to open and use the custom lore section of ICP
    default: op
  itemcreatorplus.name:
    description: allows the user to open and use the custom name section of ICP
    default: op
  itemcreatorplus.specmod:
    description: allows the user to open and use the special modifiers section of ICP
    default: op
  itemcreatorplus.takeitem:
    description: allows the user to take the item they have created in ICP
    default: true
  itemcreatorplus.nosavelimit:
    description: allows the user to have no saved item limit
    default: op
  itemcreatorplus.editoverride:
    description: allows the user to edit any items that weren't made by them (works for items made by "Unknown")
    default: op