name: ItemCreatorPlus
version: 1.8.3
author: Darkolythe
main: me.darkolythe.itemcreatorplus.ItemCreatorPlus
api-version: 1.13
description: This plugin allows easy creation of custom items with potion effects, attributes, and more, all in a simple GUI.

commands:
  itemcreatorplus:
    usage: /<command>
    aliases: [icp]
    description: the itemcreatorplus base command
    permission: itemcreatorplus.command
    permission-message: You do not have permission!

permissions:
  itemcreatorplus.command:
    description: basic command permission
    default: op
  itemcreatorplus.savemenu:
    description: lets the player open up the list of saved items
    default: op
  itemcreatorplus.giveitem:
    description: gives the user the permission to give ICP items to certain players via the /icp give command (can be used in console)
    default: op
  itemcreatorplus.enchant:
    description: allows the user to open and use the enchant section of ICP
    default: op
  itemcreatorplus.status:
    description: allows the user to open and use the status effects section of ICP
    default: op
  itemcreatorplus.saveitem:
    description: allows the user to save custom items
    default: op
  itemcreatorplus.lore:
    description: allows the user to open and use the custom lore section of ICP
    default: op
  itemcreatorplus.name:
    description: allows the user to open and use the custom name section of ICP
    default: op
  itemcreatorplus.specmod:
    description: allows the user to open and use the special modifiers section of ICP
    default: op